const { Document, Packer, Paragraph, TextRun, HeadingLevel, Footer, PageNumber } = require('docx');
const db = require('../db');
function list(value) {
  try { const parsed = JSON.parse(value || '[]'); return Array.isArray(parsed) ? parsed : []; }
  catch { return []; }
}
const clean = value => String(value ?? '').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g, '');
function utc(value) {
  if (!value) return 'Not recorded';
  const date = new Date(value.includes('T') ? value : value.replace(' ', 'T') + 'Z');
  return Number.isNaN(date.getTime()) ? clean(value) : date.toISOString().replace('T', ' ').replace(/Z$/, ' UTC');
}
function paragraph(value) {
  const lines = clean(value || 'Not recorded').split(/\r?\n/);
  return new Paragraph({ children: lines.map((text, index) => new TextRun({ text, ...(index ? { break: 1 } : {}) })), spacing: { after: 160 } });
}
function field(label, value) {
  return new Paragraph({ children: [new TextRun({ text: `${label}: `, bold: true }), new TextRun(clean(value ?? 'Not recorded'))], spacing: { after: 100 } });
}
function heading(text) { return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 300, after: 160 } }); }
function snapshot(id) {
  return db.transaction(() => {
    const incident = db.prepare('SELECT c.*, u.username AS assignee FROM cases c LEFT JOIN users u ON u.id=c.assigned_to WHERE c.id=?').get(id);
    if (!incident) return null;
    return {
      incident,
      notes: db.prepare('SELECT n.*, u.username AS author FROM case_notes n LEFT JOIN users u ON u.id=n.author_id WHERE n.case_id=? ORDER BY n.created_at,n.id').all(id),
      history: db.prepare('SELECT h.*, u.username AS actor FROM case_history h LEFT JOIN users u ON u.id=h.actor_id WHERE h.case_id=? ORDER BY h.created_at,h.id').all(id),
      iocs: db.prepare('SELECT * FROM iocs WHERE case_id=? ORDER BY id').all(id),
      tasks: db.prepare('SELECT p.name,t.*,u.username AS owner,v.username AS completed_by_name FROM case_playbooks p JOIN playbook_tasks t ON t.case_playbook_id=p.id LEFT JOIN users u ON u.id=t.assigned_to LEFT JOIN users v ON v.id=t.completed_by WHERE p.case_id=? ORDER BY p.id,t.position').all(id),
      links: db.prepare('SELECT c.id,c.title FROM case_links l JOIN cases c ON c.id=CASE WHEN l.case_id_a=? THEN l.case_id_b ELSE l.case_id_a END WHERE l.case_id_a=? OR l.case_id_b=? ORDER BY c.id').all(id,id,id),
    };
  })();
}
async function createReport(id, exporter) {
  const data = snapshot(id);
  if (!data) return null;
  const { incident: c, notes, history, tasks, links } = data;
  const caseId = `#${String(c.id).padStart(4, '0')}`;
  const children = [new Paragraph({ text: 'Nib · Incident report', heading: HeadingLevel.TITLE }),
    new Paragraph({ text: `${caseId} — ${clean(c.title)}`, heading: HeadingLevel.HEADING_1 }),
    field('Generated at', utc(new Date().toISOString())), field('Generated by', exporter),
    paragraph('Snapshot of the saved case at export time. All timestamps are UTC.'), heading('Case overview')];
  for (const [label, value] of [['Case ID', caseId], ['Status', c.status], ['Severity', c.severity], ['Assigned to', c.assignee || 'Unassigned'], ['Archived', c.archived ? 'Yes' : 'No'], ['Attack type', c.attack_type], ['Origin', c.origin_country], ['Asset', c.asset_name], ['Shift', c.shift], ['Incident time', utc(c.incident_datetime)], ['Created', utc(c.created_at)], ['Last updated', utc(c.updated_at)], ['Response deadline', utc(c.due_at)], ['Deadline source', c.deadline_source], ['Rejected by', c.rejected_by], ['Source IPs', list(c.source_ip).join(', ') || null], ['Destination IPs', list(c.destination_ip).join(', ') || null], ['HTTP status codes', list(c.http_status).join(', ') || null]]) children.push(field(label, value));
  for (const [title, value] of [['Summary', c.summary], ['Impact', c.impact], ['Recommendations', c.recommendations]]) children.push(heading(title), paragraph(value));
  children.push(heading('Indicators of compromise and evidence'));
  const iocs = data.iocs.length ? data.iocs : list(c.iocs);
  if (!iocs.length) children.push(paragraph('No indicators recorded.'));
  for (const ioc of iocs) {
    children.push(field('Indicator', `${ioc.type || 'Unknown'} — ${ioc.value || 'Not recorded'}`), field('Threat intelligence', ioc.threat_intelligence), field('Count', ioc.count), field('Percentage', ioc.percentage), paragraph(ioc.description));
    const attachments = [...(Array.isArray(ioc.images) ? ioc.images : list(ioc.images)), ...(Array.isArray(ioc.documents) ? ioc.documents : list(ioc.documents))];
    for (const file of attachments) children.push(field('Attachment', `${file.originalName || 'Unnamed file'}${file.size != null ? ` (${file.size} bytes)` : ''}`));
  }
  children.push(paragraph('Attachments are listed by filename; file contents are not embedded in this report.'));
  children.push(heading('Investigation notes'));
  if (!notes.length) children.push(paragraph('No notes recorded.'));
  for (const note of notes) children.push(field('Note', `${utc(note.created_at)} · ${note.author || 'Unknown user'}`), paragraph(note.body));
  children.push(heading('Response checklist'));
  if (!tasks.length) children.push(paragraph('No checklist tasks recorded.'));
  for (const task of tasks) children.push(field(task.name, task.title), field('Owner', task.owner || 'Unassigned'), field('Completion', task.completed_at ? `${utc(task.completed_at)} · ${task.completed_by_name || 'Unknown user'}` : 'Pending'));
  children.push(heading('Linked cases'));
  if (!links.length) children.push(paragraph('No linked cases.'));
  for (const link of links) children.push(paragraph(`#${String(link.id).padStart(4, '0')} — ${link.title}`));
  children.push(heading('Activity history'));
  if (!history.length) children.push(paragraph('No activity recorded.'));
  for (const event of history) children.push(field(event.action.replace(/_/g, ' '), `${utc(event.created_at)} · ${event.actor || 'System'}`), paragraph(event.detail));
  const doc = new Document({ creator: 'Nib', title: `Incident report ${caseId}`, styles: { default: { document: { run: { font: 'Calibri', size: 22 }, paragraph: { spacing: { after: 120 } } } } }, sections: [{ properties: {}, footers: { default: new Footer({ children: [new Paragraph({ children: [new TextRun(`Nib · ${caseId} · Page `), new TextRun({ children: [PageNumber.CURRENT] })] })] }) }, children }] });
  return Packer.toBuffer(doc);
}
module.exports = { createReport };
