const { test, expect } = require('@playwright/test');
async function login(page, username = 'analyst') {
  await page.goto('/login');
  await page.locator('form input').nth(0).fill(username);
  await page.locator('input[type=password]').fill('browser-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).not.toHaveURL(/\/login$/);
  await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible();
}
async function newCase(page, title) {
  return page.evaluate(async title => {
    const response = await fetch('/api/cases', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('nib_token')}` }, body: JSON.stringify({ title }) });
    if (!response.ok) throw new Error('Fixture creation failed');
    return response.json();
  }, title);
}
test('case report downloads a Word document from the case page', async ({ page }) => {
  await login(page);
  const incident = await newCase(page, 'Word report browser case');
  await page.goto(`/cases/${incident.id}`);
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export report (.docx)', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe(`Nib-case-${String(incident.id).padStart(4, '0')}-report.docx`);
  const fs = require('node:fs');
  const JSZip = require('../backend/node_modules/jszip');
  const zip = await JSZip.loadAsync(fs.readFileSync(await download.path()));
  expect(await zip.file('word/document.xml').async('string')).toContain('Word report browser case');
  await expect(page.getByRole('button', { name: 'Export report (.docx)', exact: true })).toBeEnabled();
});
test('sidebar hides user identity and dark mode persists across refresh', async ({ page }) => {
  await login(page, 'admin');
  const sidebar = page.getByRole('complementary');
  await expect(sidebar.getByText('admin', { exact: true })).toHaveCount(0);
  await expect(sidebar.getByText('SOC Admin', { exact: true })).toHaveCount(0);
  const toggle = sidebar.getByRole('button', { name: 'Dark mode', exact: true });
  await toggle.click();
  await expect(toggle).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.goto('/cases');
  await expect(page.locator('main').getByRole('heading', { name: 'All cases', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(sidebar.getByRole('button', { name: 'Dark mode', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await sidebar.getByRole('button', { name: 'Dark mode', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
});
test('IR rejects, admin archives and restores, then exports filtered activity', async ({ page }) => {
  await login(page, 'ir');
  const incident = await newCase(page, 'Lifecycle walkthrough');
  await page.goto(`/cases/${incident.id}`);
  page.once('dialog', dialog => dialog.accept('Confirmed false positive'));
  await page.getByRole('button', { name: 'Reject', exact: true }).click();
  await expect(page.getByText('Confirmed false positive', { exact: false }).first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'Archive case' })).toHaveCount(0);
  await page.goto('/audit');
  await expect(page).toHaveURL('http://127.0.0.1:5175/');
  await page.getByRole('button', { name: 'Log out' }).click();
  await login(page, 'admin');
  await page.goto(`/cases/${incident.id}`);
  await page.getByRole('button', { name: 'Archive case' }).click();
  await expect(page).toHaveURL(/\/archive$/);
  const archivedRow = page.getByText('Lifecycle walkthrough', { exact: true }).locator('..');
  await archivedRow.locator('..').getByRole('button', { name: 'Restore', exact: true }).click();
  await expect(page.getByText('Lifecycle walkthrough', { exact: true })).toHaveCount(0);
  await page.goto('/audit');
  await page.getByRole('textbox', { name: 'Search case activity', exact: true }).fill('Lifecycle walkthrough');
  await page.getByLabel('Action', { exact: true }).selectOption('restored');
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('tbody tr')).toHaveCount(1);
  await expect(page.locator('tbody')).toContainText('admin');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export CSV' }).click();
  const download = await downloadPromise;
  const fs = require('node:fs');
  const csv = fs.readFileSync(await download.path(), 'utf8');
  expect(csv).toContain('Lifecycle walkthrough');
  expect(csv).toContain('"restored"');
  expect(csv).not.toContain('"archived"');
  const invalid = await page.request.get('/api/audit/history?from=2026-02-31', {
    headers: { Authorization: `Bearer ${await page.evaluate(() => sessionStorage.getItem('nib_token'))}` },
  });
  expect(invalid.status()).toBe(400);
});
test('Nib sign-in persists through refresh, protects admin pages and logs out', async ({ page }) => {
  await login(page);
  await expect(page).toHaveTitle('Nib Incident Tracking System');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible();
  await page.goto('/users');
  await expect(page).toHaveURL('http://127.0.0.1:5175/');
  await expect(page.getByRole('link', { name: 'User management' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Log out' }).click();
  await expect(page).toHaveURL(/\/login$/);
});
test('incident wizard validates, uploads evidence, creates a case and preserves search on refresh', async ({ page }) => {
  await login(page);
  await page.goto('/incidents/new');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await expect(page.getByText('Please fill in all required fields.')).toBeVisible();
  await page.getByPlaceholder('Enter alert name here').fill('Browser evidence incident');
  for (const [placeholder, value] of [['Enter source IP addresses', '192.0.2.1'], ['Enter destination IP addresses', '192.0.2.2']]) {
    await page.getByPlaceholder(placeholder).fill(value);
    await page.getByPlaceholder(placeholder).press('Enter');
  }
  await page.locator('input[type=datetime-local]').fill('2026-09-28T12:00');
  for (const [index, value] of ['Mail Server', 'Unknown', 'Information Leak', 'High', 'Morning'].entries()) await page.locator('main select').nth(index).selectOption(value);
  await page.getByRole('button', { name: '403', exact: true }).click();
  await page.getByPlaceholder('Enter a brief summary of the incident here').fill('Browser workflow summary');
  await page.getByPlaceholder('Describe the impact of the incident here').fill('Test impact');
  await page.getByPlaceholder('Enter initial recommendations here').fill('Investigate');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.locator('main select').nth(0).selectOption('Domain');
  await page.locator('main select').nth(1).selectOption('Internal Threat Feed');
  await page.getByPlaceholder('Enter IOC description here').fill('browser-evidence.invalid');
  await page.locator('input[type=file]').nth(1).setInputFiles({ name: 'evidence.txt', mimeType: 'text/plain', buffer: Buffer.from('Nib browser evidence') });
  await expect(page.getByText('evidence.txt', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add IOC', exact: true }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Submit Incident' }).click();
  await expect(page).toHaveURL(/\/cases\/\d+$/);
  await expect(page.getByRole('heading', { name: 'Browser evidence incident' })).toBeVisible();
  const attachment = page.getByRole('link', { name: 'evidence.txt' });
  await expect(attachment).toBeVisible();
  const download = await page.request.get(await attachment.getAttribute('href'));
  expect(await download.text()).toBe('Nib browser evidence');
  await page.getByPlaceholder('Add a note...').fill('Browser investigation note');
  await page.getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.getByText('Browser investigation note', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'In Progress', exact: true }).click();
  await expect(page.getByText('Status changed from "Attempt" to "In Progress"')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Archive case' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Reject', exact: true })).toHaveCount(0);
  await page.getByRole('textbox', { name: 'Search cases', exact: true }).fill('Browser evidence');
  await page.getByRole('textbox', { name: 'Search cases', exact: true }).press('Enter');
  await expect(page).toHaveURL(/q=Browser%20evidence/);
  await page.reload();
  await expect(page.getByText('Browser evidence incident', { exact: true })).toBeVisible();
});
test('admin assigns a case and saves a deadline visible in due-soon workload', async ({ page }) => {
  await login(page, 'admin');
  const incident = await newCase(page, 'Browser deadline case');
  await page.goto(`/cases/${incident.id}`);
  await page.locator('main select').first().selectOption({ label: 'analyst (SOC_ANALYST)' });
  await expect(page.locator('main select').first()).toBeEnabled();
  await page.reload();
  await expect(page.locator('main select').first()).toHaveValue('1');
  const date = new Date(Date.now() + 12 * 3600000);
  // Browser context uses UTC in this suite.
  await page.getByLabel('Response deadline').fill(date.toISOString().slice(0, 16));
  await page.getByRole('button', { name: 'Save deadline' }).click();
  await expect(page.getByRole('button', { name: 'Clear', exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Due soon', exact: true }).click();
  await expect(page.getByText('Browser deadline case', { exact: true })).toBeVisible();
});
test('mobile navigation closes after selection and pages fit the viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/login');
  await page.locator('form input').nth(0).fill('analyst');
  await page.locator('input[type=password]').fill('browser-password');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).toHaveURL('http://127.0.0.1:5175/');
  await page.getByRole('button', { name: 'Toggle navigation' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'My cases', exact: true }).click();
  await expect(page).toHaveURL(/mine=1/);
  await expect(page.getByRole('button', { name: 'Close navigation' })).toHaveCount(0);
  for (const route of ['/cases?mine=1', '/incidents/new']) {
    await page.goto(route);
    await expect(page.locator('main').getByRole('heading').first()).toBeVisible();
    expect(await page.locator('main').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  }
});

test('admin creates a playbook; case tasks persist, record completion and preserve template snapshots', async ({ page }) => {
  await login(page, 'admin');
  await page.getByRole('link', { name: 'Playbooks', exact: true }).click();
  await page.getByLabel('Template name').fill('Browser investigation');
  await page.getByLabel('Description', { exact: true }).fill('Investigate and document');
  await page.getByLabel('Steps (one per line)').fill('Collect evidence\nDocument findings');
  await page.getByRole('button', { name: 'Save playbook' }).click();
  await expect(page.getByRole('status')).toContainText('Playbook saved');
  const incident = await newCase(page, 'Browser playbook case');
  await page.goto(`/cases/${incident.id}`);
  await page.getByLabel('Playbook template').selectOption({ label: 'Browser investigation' });
  await page.getByRole('button', { name: 'Attach playbook' }).click();
  await expect(page.getByText('0 of 2 tasks completed')).toBeVisible();
  await page.getByLabel('Owner for Collect evidence').selectOption({ label: 'analyst' });
  await expect(page.getByLabel('Owner for Collect evidence')).toBeEnabled();
  await page.getByRole('checkbox', { name: 'Collect evidence', exact: true }).click();
  await expect(page.getByText('1 of 2 tasks completed')).toBeVisible();
  await expect(page.getByText(/Completed by admin/)).toBeVisible();
  await page.reload();
  await expect(page.getByRole('checkbox', { name: 'Collect evidence', exact: true })).toBeChecked();
  await expect(page.getByLabel('Owner for Collect evidence')).toHaveValue('1');
  await page.goto('/playbooks');
  await page.getByRole('button', { name: 'Edit Browser investigation', exact: true }).click();
  await page.getByLabel('Steps (one per line)').fill('Replacement step');
  await page.getByLabel('Available for new cases').uncheck();
  await page.getByRole('button', { name: 'Save playbook' }).click();
  await expect(page.getByRole('status')).toContainText('Playbook saved');
  await page.getByRole('button', { name: 'Log out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, 'analyst');
  await page.goto(`/cases/${incident.id}`);
  await expect(page.getByRole('checkbox', { name: 'Collect evidence', exact: true })).toBeChecked();
  await expect(page.getByText('Document findings', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Owner for Collect evidence')).toHaveCount(0);
  await page.getByRole('checkbox', { name: 'Document findings', exact: true }).click();
  await expect(page.getByText('2 of 2 tasks completed')).toBeVisible();
  await expect(page.getByText(/Completed by analyst/)).toBeVisible();
  await page.getByRole('checkbox', { name: 'Collect evidence', exact: true }).click();
  await expect(page.getByText('1 of 2 tasks completed')).toBeVisible();
  await page.getByRole('button', { name: 'Completed', exact: true }).click();
  await expect(page.getByRole('checkbox', { name: 'Collect evidence', exact: true })).toBeDisabled();
  await page.goto('/playbooks');
  await expect(page).toHaveURL('http://127.0.0.1:5175/');
});

test('SLA policy creates automatic deadlines and supports explicit manual overrides', async ({ page }) => {
  await login(page, 'admin');
  await page.getByRole('link', { name: 'SLA policies', exact: true }).click();
  await page.getByRole('checkbox', { name: 'High', exact: true }).check();
  await page.getByLabel('High response hours', { exact: true }).fill('6');
  await page.getByRole('button', { name: 'Save SLA policies' }).click();
  await expect(page.getByRole('status').filter({ hasText: 'SLA policies saved' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('checkbox', { name: 'High', exact: true })).toBeChecked();
  const incident = await page.evaluate(async () => {
    const response = await fetch('/api/cases', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('nib_token')}` }, body: JSON.stringify({ title: 'Browser SLA incident', severity: 'High' }) });
    if (!response.ok) throw new Error('Case creation failed');
    return response.json();
  });
  expect(incident.deadline_source).toBe('sla');
  await page.goto(`/cases/${incident.id}`);
  await expect(page.getByText('Deadline source: severity SLA policy')).toBeVisible();
  await page.getByRole('button', { name: 'Clear', exact: true }).click();
  await expect(page.getByLabel('Response deadline', { exact: true })).toHaveValue('');
  await expect(page.getByText('Deadline source: manual override')).toBeVisible();
  await page.getByRole('button', { name: 'Apply current SLA policy' }).click();
  await expect(page.getByText('Deadline source: severity SLA policy')).toBeVisible();
  await page.getByRole('link', { name: 'Due soon', exact: true }).click();
  await expect(page.getByText('Browser SLA incident', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Log out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await login(page, 'analyst');
  await page.goto('/sla');
  await expect(page).toHaveURL('http://127.0.0.1:5175/');
  await page.goto(`/cases/${incident.id}`);
  await expect(page.getByText('Deadline source: severity SLA policy')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Apply current SLA policy' })).toHaveCount(0);
});
